//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class Hakkimizda
    {
        public int Id { get; set; }

        [Required]
        [Display(Name ="Üst Baþlýk")]
        public string UstBaslik { get; set; }

        [Required]
        [Display(Name = "Baþlýk")]
        public string Baslik { get; set; }
        public string aboutImage { get; set; }

        public virtual HttpPostedFileBase fotoFile { get; set; }

        [AllowHtml]
        [Required]
        [Display(Name = "Ýçerik Bilgisi")]
        public string Aciklama { get; set; }
    }
}
