//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.Web.Mvc;
    
    public partial class Urunler
    {
        public int Id { get; set; }
        public string UstBaslik { get; set; }
        public string Baslik { get; set; }
        public string urunImage { get; set; }

        public virtual HttpPostedFileBase urunFile { get; set; }

        [AllowHtml]
        public string Aciklama { get; set; }
        public bool Aktiflik { get; set; }
        public Nullable<int> Sira { get; set; }
    }
}
